### ISSUE TITLE
add_alumni.php: Dropdown for employer choice

### ISSUE THREAD

**Issue by slins1** [slins1/BRAINS#12]
Dr. Mitra wants the use of a dropdown box that employers can be selected from. However, we need to reconcile this with a way to be able to add new employers that don't yet exist in the database table for employers. Maybe an other option in the dropdown, which would activate a text box that can allow for input of company name? That doesn't cover all of the necessary information for an entry in the Employer table

**Comment by rconn4** [comment]
We decided to add another "button" in the nav bar to (add/modify/delete) employer.  I have added the dropdown to Add_Alumni.php
