### ISSUE TITLE
add_alumni.php: Validation for Personal Info (first two tables)

### ISSUE THREAD

**Issue by slins1** [slins1/BRAINS#13]
- [x] Fields which MUST be filled in:
    - First Name
    - Last Name
    - Banner ID
    - Email
- [x] Default Visibility: All checkboxes checked
- [x] Default Preferred Contact: Email
- [x] Must be at least one degree from Brockport. This will require two degree rows by default

**Comment by rconn4** [comment]
Bottom 3 bullets are finished

**Comment by rconn4** [comment]
NOTE: curdate() doesn't work with recent update to php on the holly server
